spring.application.name=fineflux
spring.data.mongodb.uri=mongodb+srv://fineflux01:Fineflux123@fineflux.kib6pew.mongodb.net/?retryWrites=true&w=majority&appName=FineFlux
spring.data.mongodb.database=Fos_FineFlux
spring.data.mongodb.aut0-index-creation=true
spring.data.mongodb.auto-index-creation=true
logging.level.com.pulse.fineflux=INFO
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG
logging.pattern.console=%-5level [%thread] %logger{36} [%X{correlationId}] - %msg%n
spring.mail.host=smtp.hostinger.com
spring.mail.port=465
spring.mail.username=reset@fineflux.com
spring.mail.password=Reset@!23
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.socketFactory.port=465
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
spring.mail.properties.mail.smtp.socketFactory.fallback=false
spring.mail.from=reset@fineflux.com
logging.level.org.springframework.mail=DEBUG

