spring.application.name=fineflux
spring.data.mongodb.uri=mongodb+srv://fineflux01:Fineflux123@fineflux.kib6pew.mongodb.net/?retryWrites=true&w=majority&appName=FineFlux
spring.data.mongodb.database=Fos_FineFlux
spring.data.mongodb.auto-index-creation=true
logging.level.com.pulse.fineflux=INFO
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG
logging.pattern.console=%-5level [%thread] %logger{36} [%X{correlationId}] - %msg%n