// src/main/java/com/pulse/fineflux/entity/Employee.java
package com.pulse.fineflux.entity;

import lombok.Getter;
import lombok.Setter;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;
import jakarta.validation.constraints.*;
import java.time.Instant;

@Setter
@Getter
@Document(collection = "employees")
public class Employee {

    // Getters and setters
    @Id
    private String id; // auto-generated by MongoDB

    @NotBlank
    private String role;

    @NotBlank
    private String department;

    @NotBlank
    private String firstName;

    @NotBlank
    private String lastName;

    // Escape + as \\+ in Java string literal for regex
    @Pattern(regexp = "^\\+?[0-9]{7,15}$", message = "Invalid phone")
    private String phoneNumber;

    @Email
    @NotBlank
    @Indexed(unique = true)
    private String emailId;

    @NotBlank
    @Indexed(unique = true)
    private String username;

    @NotBlank
    private String passwordHash; // store encoded password

    @CreatedDate
    private Instant joinedDate;

    private ShiftTiming shiftTiming;

    private Address address;

    private EmergencyContact emergencyContact;

    public Employee() {}

    @Setter
    @Getter
    public static class ShiftTiming {
        // 24h HH:mm (store as text or split into hour/minute)
        @Pattern(regexp = "^[0-2][0-9]:[0-5][0-9]$", message = "Invalid start time")
        private String start;

        @Pattern(regexp = "^[0-2][0-9]:[0-5][0-9]$", message = "Invalid end time")
        private String end;

        public ShiftTiming() {}

    }

    @Setter
    @Getter
    public static class Address {
        private String line1;
        private String line2;
        private String city;
        private String state;
        private String postalCode;
        private String country;

        public Address() {}

    }

    @Setter
    @Getter
    public static class EmergencyContact {
        @NotBlank
        private String name;

        // Escape + as \\+ in Java string literal for regex
        @Pattern(regexp = "^\\+?[0-9]{7,15}$", message = "Invalid phone")
        private String phone;

        private String relationship;

        public EmergencyContact() {}

    }
}
