package com.pulse.fineflux.entity;

import lombok.*;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.math.BigDecimal;
import java.util.Date;

@Document(collection = "inventory")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Inventory {

    @Id
    private String inventoryId; // Auto-generated by MongoDB
    private String productName;
    private BigDecimal currentStock;
    private BigDecimal totalCapacity;
    private BigDecimal stockValue;
    private Date lastUpdated; // changed from OffsetDateTime to Date
    private Integer employeeId;
    private String metric;
    private String productId; // reference to Product
    private Boolean status;
    private BigDecimal tankCapacity;
}
